name: Android Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install dependencies
      run: npm install

    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli

    - name: Build React app
      run: npm run build

    - name: Sync Android project
      run: npx cap sync android

    - name: Make Gradle executable
      run: chmod +x ./android/gradlew

    - name: Build APK
      working-directory: ./android
      run: ./build-apk-types.sh

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v2
      with:
        name: apk-files
        path: apk-output/*.apk