name: Android Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Позволяет запускать workflow вручную из GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build React app
      run: npx react-scripts build
    
    - name: Install Capacitor CLI
      run: npm install -g @capacitor/cli
    
    - name: Sync Capacitor with Android
      run: npx cap sync android
    
    - name: Выдача прав на Gradle
      run: chmod +x ./android/gradlew
    
    # Сборка только универсального APK для простоты
    - name: Build Universal APK
      working-directory: ./android
      run: |
        # Модифицируем build.gradle для включения всех архитектур
        sed -i "s/abiFilters.*/abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'/g" app/build.gradle
        ./gradlew assembleDebug
        mkdir -p ../apk-output
        cp app/build/outputs/apk/debug/app-debug.apk ../apk-output/SmartBasket-universal.apk
        
    # Выведем список созданных файлов
    - name: List APK files
      run: |
        ls -la apk-output/
        echo "=== APK файлы созданы ==="
        echo "Скачайте их вручную после завершения сборки через GitHub UI"